FROM jenkins/jenkins:lts-jdk17

USER root

# --- 1. Install Git & Build Tools ---
RUN apt-get update && apt-get install -y \
    git \
    make \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

# --- 2. Install Docker CLI + Compose Plugin ---
RUN install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | \
    gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    chmod a+r /etc/apt/keyrings/docker.gpg && \
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
      https://download.docker.com/linux/debian \
      $(lsb_release -cs) stable" \
      > /etc/apt/sources.list.d/docker.list && \
    apt-get update && \
    apt-get install -y docker-ce-cli docker-compose-plugin

# --- 3. Add Jenkins user to Docker group ---
# (biar Jenkins bisa akses /var/run/docker.sock)
RUN groupadd -f docker && usermod -aG docker jenkins

USER jenkins
